# Generated by Django 4.2 on 2023-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_messages_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
